language: python3

script:
  ## This runs the template with the default parameters, and runs test within the templated app.
  - docker build -t navicore/lots-of-names-api-py .

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push navicore/lots-of-names-api-py;
    docker tag "navicore/lots-of-names-api-py" "navicore/lots-of-names-api-py:0.1.$TRAVIS_BUILD_NUMBER";
    docker push "navicore/lots-of-names-api-py:0.1.$TRAVIS_BUILD_NUMBER";
    fi

